### ISSUE TITLE
Net error

### ISSUE THREAD

**Issue by ClassickTech** [TheTechRun/RcloneTV#1]
Getting "net::ERR_CONNECTION_REFUSED" on app startup. Any help?

**Comment by TheTechRun** [comment]
Hello. You need to open up your rclone serve port in the firewall.

**Comment by ClassickTech** [comment]
Yea I seen that in the read me after I posted. All is working well. Thanks much for this!

**Comment by ClassickTech** [comment]
Yea I seen that in the read me after I posted. All is working well. Thanks much for this!
